In [3]:
import pandas as pd

In [3]:
logon=pd.read_csv("../data/raw/archive/r4.2/logon.csv")

In [ ]:
logon.head()

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

In [5]:
logon.info()

<class 'pandas.DataFrame'>
RangeIndex: 854859 entries, 0 to 854858
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        854859 non-null  str
 1   date      854859 non-null  str
 2   user      854859 non-null  str
 3   pc        854859 non-null  str
 4   activity  854859 non-null  str
dtypes: str(5)
memory usage: 32.6 MB

In [7]:
logon.shape

(854859, 5)

In [10]:
logon.isnull().sum()

id          0
date        0
user        0
pc          0
activity    0
dtype: int64

In [18]:
list(logon.columns)

['id', 'date', 'user', 'pc', 'activity']

In [19]:
device=pd.read_csv("../data/raw/archive/r4.2/device.csv")

In [20]:
device.columns

Index(['id', 'date', 'user', 'pc', 'activity'], dtype='str')

In [21]:
device.head()

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect
3  {H0Z7-E6GB57XZ-1603MOXD}  01/02/2010 07:59:49  IIW0249  PC-0843     Connect
4  {L7P2-G4PX02RX-7999GYOY}  01/02/2010 08:04:26  IIW0249  PC-0843  Disconnect

In [22]:
device.isnull().sum()

id          0
date        0
user        0
pc          0
activity    0
dtype: int64

In [23]:
device.info()

<class 'pandas.DataFrame'>
RangeIndex: 405380 entries, 0 to 405379
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        405380 non-null  str
 1   date      405380 non-null  str
 2   user      405380 non-null  str
 3   pc        405380 non-null  str
 4   activity  405380 non-null  str
dtypes: str(5)
memory usage: 15.5 MB

In [24]:
device.shape

(405380, 5)

In [13]:
email=pd.read_csv("../data/raw/archive/r4.2/email.csv")

In [10]:
file=pd.read_csv("../data/raw/archive/r4.2/file.csv")

In [5]:
http=pd.read_csv("../data/raw/archive/r4.2/http.csv",nrows=5000)

In [6]:
http.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       5000 non-null   str
 1   date     5000 non-null   str
 2   user     5000 non-null   str
 3   pc       5000 non-null   str
 4   url      5000 non-null   str
 5   content  5000 non-null   str
dtypes: str(6)
memory usage: 234.5 KB

In [8]:
http.shape

(5000, 6)

In [11]:
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 445581 entries, 0 to 445580
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        445581 non-null  str
 1   date      445581 non-null  str
 2   user      445581 non-null  str
 3   pc        445581 non-null  str
 4   filename  445581 non-null  str
 5   content   445581 non-null  str
dtypes: str(6)
memory usage: 20.4 MB

In [14]:
email.info()

<class 'pandas.DataFrame'>
RangeIndex: 2629979 entries, 0 to 2629978
Data columns (total 11 columns):
 #   Column       Dtype
---  ------       -----
 0   id           str
 1   date         str
 2   user         str
 3   pc           str
 4   to           str
 5   cc           str
 6   bcc          str
 7   from         str
 8   size         int64
 9   attachments  int64
 10  content      str
dtypes: int64(2), str(9)
memory usage: 220.7 MB

In [15]:
psychometric = pd.read_csv("../data/raw/archive/r4.2/psychometric.csv")

In [17]:
psychometric.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  1000 non-null   str
 1   user_id        1000 non-null   str
 2   O              1000 non-null   int64
 3   C              1000 non-null   int64
 4   E              1000 non-null   int64
 5   A              1000 non-null   int64
 6   N              1000 non-null   int64
dtypes: int64(5), str(2)
memory usage: 54.8 KB

In [18]:
psychometric.shape

(1000, 7)

In [19]:
psychometric.isnull().sum()

employee_name    0
user_id          0
O                0
C                0
E                0
A                0
N                0
dtype: int64

In [21]:
psychometric.columns

Index(['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N'], dtype='str')

In [22]:
psychometric.head()

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

In [23]:
email.columns

Index(['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size',
       'attachments', 'content'],
      dtype='str')

In [24]:
http.columns

Index(['id', 'date', 'user', 'pc', 'url', 'content'], dtype='str')

In [25]:
file.info

<bound method DataFrame.info of                               id                 date     user       pc  \
0       {L9G8-J9QE34VM-2834VDPB}  01/02/2010 07:23:14  MOH0273  PC-6699
1       {H0W6-L4FG38XG-9897XTEN}  01/02/2010 07:26:19  MOH0273  PC-6699
2       {M3Z0-O2KK89OX-5716MBIM}  01/02/2010 08:12:03  HPH0075  PC-2417
3       {E1I4-S4QS61TG-3652YHKR}  01/02/2010 08:17:00  HPH0075  PC-2417
4       {D4R7-E7JL45UX-0067XALT}  01/02/2010 08:24:57  HSB0196  PC-8001
...                          ...                  ...      ...      ...
445576  {J2Q8-Z4UX02QT-2675RTJI}  05/16/2011 23:22:31  IBB0359  PC-3620
445577  {S3G4-K5PB37EL-4663ADOI}  05/16/2011 23:22:32  IBB0359  PC-3620
445578  {G6G8-X7JK94JA-2703OXCY}  05/16/2011 23:22:33  IBB0359  PC-3620
445579  {H8U9-F5GM78QB-9540DSQM}  05/16/2011 23:22:33  IBB0359  PC-3620
445580  {O7W5-J7UI71TW-2695JVNC}  05/16/2011 23:22:34  IBB0359  PC-3620

            filename                                            content
0       EYPC9Y08.doc  D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1       N3LTSU3O.pdf  25-50-44-46-2D carpenters 25 landed strait dis...
2       D3D3WC9W.doc  D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...
3       QCSW62YS.doc  D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...
4       AU75JV6U.jpg                                              FF-D8
...              ...                                                ...
445576  R8DTDN2Q.txt  5A-44-4F-39 government operations led wound co...
445577  BLHCRL6W.pdf  25-50-44-46-2D throughout 20 once armed southe...
445578  ZHMDTTW0.doc  D0-CF-11-E0-A1-B1-1A-E1 companies river englan...
445579  AC0QL6KF.pdf  25-50-44-46-2D member august observed selected...
445580  OQYLA67J.doc  D0-CF-11-E0-A1-B1-1A-E1 insurance which brothe...

[445581 rows x 6 columns]>

In [26]:
file.columns

Index(['id', 'date', 'user', 'pc', 'filename', 'content'], dtype='str')

In [28]:
http.info

<bound method DataFrame.info of                             id                 date     user       pc  \
0     {V1Y4-S2IR20QU-6154HFXJ}  01/02/2010 06:55:16  LRR0148  PC-4275
1     {Q5R1-T3EF87UE-2395RWZS}  01/02/2010 07:00:13  NGF0157  PC-6056
2     {X9O1-O0XW52VO-5806RPHG}  01/02/2010 07:03:46  NGF0157  PC-6056
3     {G5S8-U5OG04TE-5299CCTU}  01/02/2010 07:05:26  IRM0931  PC-7188
4     {L0R4-A9DH29VP-4553AUWM}  01/02/2010 07:05:52  IRM0931  PC-7188
...                        ...                  ...      ...      ...
4995  {P8J3-D1JP22WX-6466GWLO}  01/03/2010 09:54:35  BVC0790  PC-0008
4996  {U6R2-H2ZA99WZ-8830BVUH}  01/03/2010 09:54:45  CMB0912  PC-6539
4997  {L1S5-P6JE33ON-4720CJJK}  01/03/2010 09:54:49  MAD0496  PC-2244
4998  {U6A2-Z4QP29KR-2356KUOU}  01/03/2010 09:55:02  CMB0912  PC-6539
4999  {T2A9-C2CW19GB-2088SWPD}  01/03/2010 09:55:04  LDD0560  PC-3683

                                                    url  \
0     http://msn.com/The_Human_Centipede_First_Seque...
1     http://urbanspoon.com/Plunketts_Creek_Loyalsoc...
2     http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...
3     http://groupon.com/Leonhard_Euler/leonhard/tne...
4     http://flickr.com/Inauguration_of_Barack_Obama...
...                                                 ...
4995  http://ibtimes.com/Halifax_Gibbet/infangtheof/...
4996  http://babycenter.com/NagornoKarabakh_War/kara...
4997  http://fidelity.com/Candide/cungonde/ohggbaovy...
4998  http://inbox.com/Cheadle_Hulme/hulme/yrnqrefuv...
4999  http://mediafire.com/Nathu_La/yadong/gernqzvyy...

                                                content
0     remain representatives consensus concert altho...
1     festival off northwards than congestion partne...
2     long away reorganized baldwin seth business 18...
3     among german schwein experimental becomes prev...
4     kate criteria j 2008 highest 12 include books ...
...                                                 ...
4995  made tv specifically number publicly leading 1...
4996  marcus 112 35 leading non hall two another ine...
4997  helping in club during grade 59 ed young origi...
4998  institution pieces march philip mid trouble co...
4999  unarmed became kind other prisoners is quarter...

[5000 rows x 6 columns]>